#!/usr/bin/env python3
"""
Train the primary ANN once (full train, no cap) and export small, LaTeX-ready
tables for qualitative plots (pred-vs-true scatter + residual histogram).

Why this exists:
  - The final report is capped to 4 pages, so we want compact but high-signal
    qualitative figures.
  - This repo avoids pandas/matplotlib; we output pgfplots tables directly.

Output:
  - Writes a small .tex snippet containing two \\pgfplotstableread blocks.
"""

from __future__ import annotations

import argparse
import copy
import time
from pathlib import Path

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Subset

from train_ann import PriceANN, TensorDataset, make_splits


def _parse_int_list(s: str) -> list[int]:
    out: list[int] = []
    for part in s.split(","):
        part = part.strip()
        if not part:
            continue
        out.append(int(part))
    if not out:
        raise ValueError("Expected a comma-separated list of integers, e.g. 512,256,128,64")
    return out


def _train_best_checkpoint(
    *,
    payload: dict,
    train_idx: list[int],
    val_idx: list[int],
    seed: int,
    hidden_dims: list[int],
    dropout: float,
    embed_dim_cap: int,
    epochs: int,
    batch_size: int,
    lr: float,
    weight_decay: float,
    device: torch.device,
) -> tuple[nn.Module, int]:
    ds = TensorDataset(payload)
    torch.manual_seed(seed)
    g = torch.Generator().manual_seed(seed)

    train_loader = DataLoader(Subset(ds, train_idx), batch_size=batch_size, shuffle=True, generator=g)
    val_loader = DataLoader(Subset(ds, val_idx), batch_size=batch_size, shuffle=False)

    cat_sizes = [len(payload["cat_maps"][col]) for col in payload["cat_cols"]]
    model = PriceANN(
        n_num=int(payload["X_num"].shape[1]),
        cat_sizes=cat_sizes,
        hidden_dims=hidden_dims,
        dropout=dropout,
        embed_dim_cap=embed_dim_cap,
    ).to(device)

    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    loss_fn = nn.MSELoss()
    mse_sum_fn = nn.MSELoss(reduction="sum")

    best_val = float("inf")
    best_epoch = 1
    best_state: dict | None = None

    for epoch in range(1, epochs + 1):
        model.train()
        for x_num, x_cat, y in train_loader:
            opt.zero_grad(set_to_none=True)
            pred = model(x_num.to(device), x_cat.to(device))
            loss = loss_fn(pred, y.to(device))
            loss.backward()
            opt.step()

        model.eval()
        val_sum = 0.0
        n_val = 0
        with torch.no_grad():
            for x_num, x_cat, y in val_loader:
                pred = model(x_num.to(device), x_cat.to(device))
                val_sum += float(mse_sum_fn(pred, y.to(device)).item())
                n_val += int(y.shape[0])
        val_mse = val_sum / max(1, n_val)

        if val_mse < best_val:
            best_val = val_mse
            best_epoch = epoch
            best_state = copy.deepcopy(model.state_dict())

    if best_state is not None:
        model.load_state_dict(best_state)

    return model, int(best_epoch)


@torch.no_grad()
def _predict_log1p(
    *,
    model: nn.Module,
    payload: dict,
    idx: list[int],
    batch_size: int,
    device: torch.device,
) -> tuple[np.ndarray, np.ndarray]:
    ds = TensorDataset(payload)
    loader = DataLoader(Subset(ds, idx), batch_size=batch_size, shuffle=False)

    y_true: list[np.ndarray] = []
    y_pred: list[np.ndarray] = []
    model.eval()
    for x_num, x_cat, y in loader:
        pred = model(x_num.to(device), x_cat.to(device)).detach().cpu().numpy().reshape(-1)
        y_true.append(y.detach().cpu().numpy().reshape(-1))
        y_pred.append(pred)

    return np.concatenate(y_true, axis=0), np.concatenate(y_pred, axis=0)


def _write_tex(
    *,
    out_path: Path,
    run_name: str,
    ape_pcts: dict[str, float],
    scatter_true: np.ndarray,
    scatter_pred: np.ndarray,
    resid_centers: np.ndarray,
    resid_counts: np.ndarray,
    by_price_decile: dict[str, np.ndarray],
    by_year: dict[str, np.ndarray] | None,
) -> None:
    header = [
        "% Auto-generated by make_ann_qual_data.py",
        f"% run_name: {run_name}",
        "",
        "% APE percentiles on the full test split (price space; percent).",
        f"\\newcommand{{\\AnnApeP50}}{{{ape_pcts['p50']:.2f}}}",
        f"\\newcommand{{\\AnnApeP90}}{{{ape_pcts['p90']:.2f}}}",
        f"\\newcommand{{\\AnnApeP95}}{{{ape_pcts['p95']:.2f}}}",
        f"\\newcommand{{\\AnnApeP99}}{{{ape_pcts['p99']:.2f}}}",
        "",
        "\\pgfplotstableread[col sep=space]{",
        "true pred",
    ]
    scatter_lines = [f"{float(t):.6f} {float(p):.6f}" for t, p in zip(scatter_true, scatter_pred, strict=False)]
    footer_scatter = ["}\\AnnPredScatter", ""]

    hist_header = ["\\pgfplotstableread[col sep=space]{", "center count"]
    hist_lines = [f"{float(c):.6f} {int(n)}" for c, n in zip(resid_centers, resid_counts, strict=False)]
    hist_footer = ["}\\AnnResidHist", ""]

    dec_header = ["\\pgfplotstableread[col sep=space]{", "decile acc mdape n lo hi"]
    dec_lines = []
    for dec, acc, mdape, n, lo, hi in zip(
        by_price_decile["decile"],
        by_price_decile["acc"],
        by_price_decile["mdape"],
        by_price_decile["n"],
        by_price_decile["lo"],
        by_price_decile["hi"],
        strict=False,
    ):
        dec_lines.append(f"{int(dec)} {float(acc):.6f} {float(mdape):.6f} {int(n)} {float(lo):.1f} {float(hi):.1f}")
    dec_footer = ["}\\AnnByPriceDecile", ""]

    year_block: list[str] = []
    if by_year is not None:
        year_header = ["\\pgfplotstableread[col sep=space]{", "year acc mdape n"]
        year_lines = []
        for yr, acc, mdape, n in zip(
            by_year["year"],
            by_year["acc"],
            by_year["mdape"],
            by_year["n"],
            strict=False,
        ):
            year_lines.append(f"{int(yr)} {float(acc):.6f} {float(mdape):.6f} {int(n)}")
        year_footer = ["}\\AnnByYear", ""]
        year_block = year_header + year_lines + year_footer

    text = "\n".join(
        header
        + scatter_lines
        + footer_scatter
        + hist_header
        + hist_lines
        + hist_footer
        + dec_header
        + dec_lines
        + dec_footer
        + year_block
    ) + "\n"
    out_path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="ann_tensors_full.pt")
    parser.add_argument("--out-tex", default="ann_qual_data.tex")
    parser.add_argument("--run-name", default="ann_qual_seed42")

    parser.add_argument("--split-strategy", choices=["random", "time"], default="random")
    parser.add_argument("--split-seed", type=int, default=42)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--hidden-dims", default="512,256,128,64")
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--embed-dim-cap", type=int, default=64)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--lr", type=float, default=0.004)
    parser.add_argument("--weight-decay", type=float, default=0.001)

    parser.add_argument("--sample-n", type=int, default=160)
    parser.add_argument("--sample-seed", type=int, default=0)
    parser.add_argument("--hist-min", type=float, default=-1.0)
    parser.add_argument("--hist-max", type=float, default=1.0)
    parser.add_argument("--hist-bins", type=int, default=40)

    args = parser.parse_args()

    started = time.time()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    payload = torch.load(args.data, map_location="cpu")

    train_idx, val_idx, test_idx = make_splits(
        payload=payload,
        train_frac=0.70,
        val_frac=0.15,
        test_frac=0.15,
        seed=args.split_seed,
        strategy=args.split_strategy,
    )

    hidden_dims = _parse_int_list(args.hidden_dims)
    model, best_epoch = _train_best_checkpoint(
        payload=payload,
        train_idx=train_idx,
        val_idx=val_idx,
        seed=args.seed,
        hidden_dims=hidden_dims,
        dropout=args.dropout,
        embed_dim_cap=args.embed_dim_cap,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        weight_decay=args.weight_decay,
        device=device,
    )

    y_true, y_pred = _predict_log1p(model=model, payload=payload, idx=test_idx, batch_size=max(1024, args.batch_size), device=device)
    resid = y_pred - y_true

    # Price-space APE distribution (full test set).
    eps = 1e-8
    true_price = np.expm1(y_true).astype(np.float64)
    pred_price = np.expm1(y_pred).astype(np.float64)
    ape = np.abs(pred_price - true_price) / np.maximum(true_price, eps)
    ape_pcts = {
        "p50": float(100.0 * np.quantile(ape, 0.50)),
        "p90": float(100.0 * np.quantile(ape, 0.90)),
        "p95": float(100.0 * np.quantile(ape, 0.95)),
        "p99": float(100.0 * np.quantile(ape, 0.99)),
    }

    rng = np.random.default_rng(args.sample_seed)
    n = int(y_true.shape[0])
    k = min(int(args.sample_n), n)
    pick = rng.choice(n, size=k, replace=False)
    scatter_true = y_true[pick]
    scatter_pred = y_pred[pick]

    hist_edges = np.linspace(float(args.hist_min), float(args.hist_max), int(args.hist_bins) + 1, dtype=np.float64)
    counts, edges = np.histogram(resid, bins=hist_edges)
    centers = (edges[:-1] + edges[1:]) / 2.0

    # Error by true-price decile (qualitative segmentation).
    order = np.argsort(true_price)
    edges_idx = np.linspace(0, n, 11, dtype=np.int64)
    deciles = np.arange(1, 11, dtype=np.int64)
    dec_acc: list[float] = []
    dec_mdape: list[float] = []
    dec_n: list[int] = []
    dec_lo: list[float] = []
    dec_hi: list[float] = []
    for d in range(10):
        lo_i = int(edges_idx[d])
        hi_i = int(edges_idx[d + 1])
        idx = order[lo_i:hi_i]
        if idx.size == 0:
            dec_acc.append(float("nan"))
            dec_mdape.append(float("nan"))
            dec_n.append(0)
            dec_lo.append(float("nan"))
            dec_hi.append(float("nan"))
            continue
        md = float(np.median(ape[idx]))
        dec_mdape.append(md)
        dec_acc.append(float(max(0.0, 100.0 * (1.0 - md))))
        dec_n.append(int(idx.size))
        lo_p = float(np.min(true_price[idx]))
        hi_p = float(np.max(true_price[idx]))
        dec_lo.append(lo_p)
        dec_hi.append(hi_p)
    by_price_decile = {
        "decile": deciles,
        "acc": np.array(dec_acc, dtype=np.float64),
        "mdape": np.array(dec_mdape, dtype=np.float64),
        "n": np.array(dec_n, dtype=np.int64),
        "lo": np.array(dec_lo, dtype=np.float64),
        "hi": np.array(dec_hi, dtype=np.float64),
    }

    # Optional: error by year (only if TransactionYear exists in numeric_cols).
    by_year = None
    numeric_cols = list(payload.get("numeric_cols", []))
    stats = payload.get("num_stats", {})
    if "TransactionYear" in numeric_cols:
        yi = numeric_cols.index("TransactionYear")
        y_std = payload["X_num"][test_idx, yi].detach().cpu().numpy().astype(np.float64)
        if "TransactionYear" in stats:
            mean = float(stats["TransactionYear"]["mean"])
            std = float(stats["TransactionYear"]["std"])
            y_raw = y_std * std + mean
        else:
            y_raw = y_std
        years = np.rint(y_raw).astype(np.int64)
        uniq = np.unique(years)
        yrs: list[int] = []
        accs: list[float] = []
        mdapes: list[float] = []
        ns: list[int] = []
        for yr in uniq:
            m = years == yr
            if not np.any(m):
                continue
            md = float(np.median(ape[m]))
            yrs.append(int(yr))
            mdapes.append(md)
            accs.append(float(max(0.0, 100.0 * (1.0 - md))))
            ns.append(int(np.sum(m)))
        by_year = {
            "year": np.array(yrs, dtype=np.int64),
            "acc": np.array(accs, dtype=np.float64),
            "mdape": np.array(mdapes, dtype=np.float64),
            "n": np.array(ns, dtype=np.int64),
        }

    out_path = Path(args.out_tex)
    _write_tex(
        out_path=out_path,
        run_name=f"{args.run_name} split={args.split_strategy} split_seed={args.split_seed} seed={args.seed} best_epoch={best_epoch}",
        ape_pcts=ape_pcts,
        scatter_true=scatter_true,
        scatter_pred=scatter_pred,
        resid_centers=centers,
        resid_counts=counts,
        by_price_decile=by_price_decile,
        by_year=by_year,
    )

    elapsed = time.time() - started
    print(f"Wrote: {out_path}  sample_n={k}  best_epoch={best_epoch}  elapsed={elapsed/60:.1f} min")


if __name__ == "__main__":
    main()
