#!/usr/bin/env python3
"""
Generate lots of report-ready graphs from the single canonical results CSV.

Why HTML (Plotly) instead of PNG:
  - This environment's compiled plotting stack (matplotlib) is broken due to
    a NumPy ABI mismatch, but Plotly graph_objects works fine and produces
    interactive, exportable charts.
  - In the HTML, each chart has a camera icon ("Download plot as png").

Inputs:
  - results_all.csv (required; tracked)
  - feature_importance_results.csv (optional; generated by feature_importance.py)
  - ann_tensors_full.pt (optional; for a few dataset context charts)

Output:
  - plots/report_graphs.html (generated; should be gitignored)
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import math
import random
import re
from pathlib import Path
from statistics import mean, stdev
from itertools import count
import json

import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
from plotly.offline import get_plotlyjs
from plotly.subplots import make_subplots


def _load_csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _f(v: object) -> float | None:
    try:
        s = str(v).strip()
        if s == "":
            return None
        return float(s)
    except Exception:
        return None


def _i(v: object) -> int | None:
    try:
        s = str(v).strip()
        if s == "":
            return None
        return int(float(s))
    except Exception:
        return None


def _is_full_random(row: dict) -> bool:
    return (row.get("feature_set") == "full") and ((row.get("split_strategy") or "random") == "random")


def _best_row(rows: list[dict], *, pred, key: str, mode: str) -> dict | None:
    best: dict | None = None
    best_val: float | None = None
    for r in rows:
        if not pred(r):
            continue
        v = _f(r.get(key, ""))
        if v is None or math.isnan(v):
            continue
        if best is None:
            best, best_val = r, v
            continue
        assert best_val is not None
        if mode == "min" and v < best_val:
            best, best_val = r, v
        elif mode == "max" and v > best_val:
            best, best_val = r, v
    return best


def _short_name(row: dict) -> str:
    src = row.get("source", "")
    if src == "train_ann":
        return f"train_ann:{row.get('run_name','')}"
    if src == "hedonic":
        return "hedonic"
    return str(row.get("name", "") or row.get("run_name", "") or "").strip()


def _hover(row: dict) -> str:
    parts = [
        f"source={row.get('source','')}",
        f"stage={row.get('stage','')}",
        f"model={row.get('model','')}",
        f"feature_set={row.get('feature_set','')}",
        f"split_strategy={row.get('split_strategy','')}",
        f"split_seed={row.get('split_seed','')}",
        f"seed={row.get('seed','')}",
        f"train_max_samples={row.get('train_max_samples','')}",
        f"name={_short_name(row)}",
        f"test_rmse={row.get('test_rmse','')}",
        f"test_acc_pct={row.get('test_acc_pct','')}",
        f"val_rmse={row.get('val_rmse','')}",
        f"val_acc_pct={row.get('val_acc_pct','')}",
        f"val_acc_pct_last={row.get('val_acc_pct_last','')}",
    ]
    return "<br>".join(parts)


_FIG_COUNTER = count(1)


def _slugify(s: str, *, max_len: int = 70) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    s = re.sub(r"_+", "_", s)
    if not s:
        s = "figure"
    if len(s) > max_len:
        s = s[:max_len].rstrip("_")
    return s


def _add_fig_section(sections: list[str], title: str, fig: go.Figure, *, registry: list[dict]) -> None:
    idx = next(_FIG_COUNTER)
    slug = _slugify(title)
    fig_id = f"fig_{idx:02d}_{slug}"
    filename = fig_id
    registry.append({"id": fig_id, "filename": filename, "title": title})

    div = pio.to_html(
        fig,
        include_plotlyjs=False,
        full_html=False,
        div_id=fig_id,
        config={
            "displaylogo": False,
            "responsive": True,
        },
    )
    actions = (
        "<div class='actions'>"
        f"<button class='btn' onclick=\"downloadFig('{fig_id}','png','{filename}')\">Download PNG</button>"
        f"<button class='btn secondary' onclick=\"downloadFig('{fig_id}','svg','{filename}')\">Download SVG</button>"
        "</div>"
    )
    sections.append(f"<section class='card'><div class='card-head'><h2>{title}</h2>{actions}</div>{div}</section>")


def _make_best_bar(rows: list[dict], *, metric: str, mode: str, title: str) -> go.Figure:
    families = [
        ("ANN (full train)", lambda r: r.get("source") == "train_ann" and _is_full_random(r)),
        ("Hedonic (full train)", lambda r: r.get("source") == "hedonic" and _is_full_random(r)),
        ("DeepFM (full train)", lambda r: r.get("source") == "train_deepfm" and _is_full_random(r)),
        ("DeepFM sweep (50k)", lambda r: r.get("source") == "sweep_deepfm" and _is_full_random(r)),
        ("ANN sweep (deep_test)", lambda r: r.get("source") == "sweep_deep_test" and _is_full_random(r)),
        ("ANN sweep (clean)", lambda r: r.get("source") == "sweep_clean" and _is_full_random(r)),
        ("FM sweep (50k)", lambda r: r.get("source") == "sweep_fm" and _is_full_random(r)),
        ("TabNet sweep (50k)", lambda r: r.get("source") == "sweep_tabnet" and _is_full_random(r)),
    ]

    picked: list[tuple[str, dict]] = []
    for label, pred in families:
        r = _best_row(rows, pred=pred, key=metric, mode=mode)
        if r is None:
            continue
        picked.append((label, r))

    # Sort by the metric (direction-aware) for readability.
    picked.sort(key=lambda kv: _f(kv[1].get(metric, "")) or (float("inf") if mode == "min" else -float("inf")), reverse=(mode == "max"))

    x = [lbl for lbl, _ in picked]
    y = [_f(r.get(metric, "")) for _, r in picked]
    text = []
    hover = []
    for _, r in picked:
        acc = _f(r.get("test_acc_pct", ""))
        rmse = _f(r.get("test_rmse", ""))
        if metric == "test_rmse":
            text.append(f"{rmse:.3f}" if rmse is not None else "")
        else:
            text.append(f"{acc:.2f}%" if acc is not None else "")
        hover.append(_hover(r))

    fig = go.Figure(
        data=[
            go.Bar(
                x=x,
                y=y,
                text=text,
                textposition="outside",
                hovertext=hover,
                hoverinfo="text",
            )
        ]
    )
    fig.update_layout(
        title=title,
        yaxis_title=metric,
        xaxis_title="Model family (best run per family)",
        height=520,
        margin=dict(l=50, r=30, t=70, b=120),
    )
    fig.update_xaxes(tickangle=-25)
    return fig


def _make_sweep_scatter(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("ANN sweep (clean)", "sweep_clean"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]

    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("test_rmse", ""))
            y = _f(r.get("test_acc_pct", ""))
            if x is None or y is None:
                continue
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                opacity=0.55,
                marker=dict(size=7),
                hovertext=hover,
                hoverinfo="text",
            )
        )

    fig.update_layout(
        title=title,
        xaxis_title="Test RMSE (log1p price) — lower is better",
        yaxis_title="Test accuracy % (MdAPE-based) — higher is better",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_val_vs_test(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("val_acc_pct", ""))
            y = _f(r.get("test_acc_pct", ""))
            if x is None or y is None:
                continue
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                opacity=0.55,
                marker=dict(size=7),
                hovertext=hover,
                hoverinfo="text",
            )
        )
    fig.update_layout(
        title=title,
        xaxis_title="Validation accuracy % (MdAPE-based)",
        yaxis_title="Test accuracy % (MdAPE-based)",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_rmse_hist(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("test_rmse", ""))
            if x is None:
                continue
            xs.append(x)
        if not xs:
            continue
        fig.add_trace(go.Histogram(x=xs, name=label, opacity=0.55, nbinsx=60))
    fig.update_layout(
        title=title,
        barmode="overlay",
        xaxis_title="Test RMSE (log1p price)",
        yaxis_title="Count",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_overfit_box(rows: list[dict], *, title: str, metric_best: str, metric_last: str, y_title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        ys: list[float] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            a = _f(r.get(metric_best, ""))
            b = _f(r.get(metric_last, ""))
            if a is None or b is None:
                continue
            ys.append(a - b)
        if not ys:
            continue
        fig.add_trace(go.Box(y=ys, name=label, boxmean="sd"))
    fig.update_layout(
        title=title,
        yaxis_title=y_title,
        height=520,
        margin=dict(l=60, r=30, t=70, b=80),
    )
    return fig


def _make_eval_points(rows: list[dict], *, split_strategy: str, metric: str, title: str) -> go.Figure:
    eval_rows = [r for r in rows if r.get("source") == "eval_suite" and (r.get("split_strategy") == split_strategy)]
    # run_name identifies the model family in eval_suite.
    run_names = [
        ("ANN best config", "ann_best_full"),
        ("Hedonic baseline", "hedonic_full"),
    ]
    fig = go.Figure()
    for label, rn in run_names:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in eval_rows:
            if r.get("run_name") != rn:
                continue
            split_seed = _i(r.get("split_seed", ""))
            seed = _i(r.get("seed", ""))
            y = _f(r.get(metric, ""))
            if split_seed is None or seed is None or y is None:
                continue
            # small jitter so overlapping seeds are visible
            x = float(split_seed) + (float(seed) - 0.5) * 0.15
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                marker=dict(size=11),
                hovertext=hover,
                hoverinfo="text",
            )
        )
    fig.update_layout(
        title=title,
        xaxis_title="Split seed (jittered by model seed)",
        yaxis_title=metric,
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    return fig


def _make_eval_mean_bars(rows: list[dict], *, metric: str, title: str) -> go.Figure:
    eval_rows = [r for r in rows if r.get("source") == "eval_suite" and r.get("feature_set") == "full"]
    groups = [
        ("ANN best config", "ann_best_full"),
        ("Hedonic baseline", "hedonic_full"),
    ]
    strategies = ["random", "time"]

    fig = go.Figure()
    for label, rn in groups:
        ys = []
        err = []
        for strat in strategies:
            vals = [_f(r.get(metric, "")) for r in eval_rows if r.get("run_name") == rn and r.get("split_strategy") == strat]
            vals = [v for v in vals if v is not None]
            if not vals:
                ys.append(None)
                err.append(0.0)
            else:
                ys.append(mean(vals))
                err.append(stdev(vals) if len(vals) > 1 else 0.0)
        fig.add_trace(
            go.Bar(
                x=strategies,
                y=ys,
                name=label,
                error_y=dict(type="data", array=err, visible=True),
            )
        )
    fig.update_layout(
        title=title,
        barmode="group",
        xaxis_title="Split strategy",
        yaxis_title=metric,
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    return fig


def _make_feature_importance(fi_path: Path) -> list[tuple[str, go.Figure]]:
    rows = _load_csv_rows(fi_path)
    if not rows:
        return []

    out: list[tuple[str, go.Figure]] = []
    for model in ["ann_mlp", "hedonic_linear_fixed_effects"]:
        subset = [r for r in rows if r.get("model") == model]
        subset.sort(key=lambda r: float(r.get("delta_val_mse", "0") or 0.0), reverse=True)
        top = subset[:15]
        names = [f"{r.get('feature_type')}:{r.get('feature_name')}" for r in top][::-1]
        vals = [float(r.get("delta_val_mse", "0") or 0.0) for r in top][::-1]
        fig = go.Figure(data=[go.Bar(x=vals, y=names, orientation="h")])
        fig.update_layout(
            title=f"Permutation importance (top 15 by Δval_mse) — {model}",
            xaxis_title="Increase in validation MSE when permuted (Δval_mse)",
            yaxis_title="Feature",
            height=620,
            margin=dict(l=180, r=30, t=70, b=60),
        )
        out.append((f"Feature importance — {model}", fig))

    # ANN vs Hedonic scatter for shared features.
    by_feat: dict[str, dict[str, float]] = {}
    for r in rows:
        key = f"{r.get('feature_type')}:{r.get('feature_name')}"
        by_feat.setdefault(key, {})
        by_feat[key][r.get("model", "")] = float(r.get("delta_val_mse", "0") or 0.0)
    xs = []
    ys = []
    text = []
    for feat, d in by_feat.items():
        if "ann_mlp" not in d or "hedonic_linear_fixed_effects" not in d:
            continue
        xs.append(d["hedonic_linear_fixed_effects"])
        ys.append(d["ann_mlp"])
        text.append(feat)

    max_v = max(xs + ys) if xs and ys else 1.0
    line = np.linspace(0, max_v, 50)
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=line, y=line, mode="lines", name="y=x", line=dict(dash="dash")))
    fig.add_trace(go.Scatter(x=xs, y=ys, mode="markers", name="Features", text=text, hoverinfo="text+x+y"))
    fig.update_layout(
        title="Permutation importance comparison (Δval_mse): ANN vs Hedonic",
        xaxis_title="Δval_mse (hedonic)",
        yaxis_title="Δval_mse (ANN)",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    out.append(("Feature importance — ANN vs Hedonic", fig))
    return out


def _make_data_context(payload_path: Path, *, sample_n: int, seed: int) -> list[tuple[str, go.Figure]]:
    if not payload_path.exists():
        return []
    import torch  # local import to keep script usable without torch in other envs

    payload = torch.load(payload_path, map_location="cpu")
    y_log = payload["y_log1p"].view(-1)

    n = int(y_log.shape[0])
    rng = random.Random(seed)
    idx = rng.sample(range(n), k=min(sample_n, n))
    y_log_s = y_log[idx].numpy()
    y_s = np.expm1(y_log_s)

    figs: list[tuple[str, go.Figure]] = []

    fig = go.Figure()
    fig.add_trace(go.Histogram(x=y_log_s, nbinsx=80))
    fig.update_layout(
        title="Target distribution: log1p(TransactionPrice) (sample)",
        xaxis_title="log1p(price)",
        yaxis_title="Count",
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    figs.append(("Data context — log1p(price) distribution", fig))

    fig = go.Figure()
    fig.add_trace(go.Histogram(x=y_s, nbinsx=80))
    fig.update_layout(
        title="Target distribution: TransactionPrice (sample; log x-axis)",
        xaxis_title="price ($)",
        yaxis_title="Count",
        xaxis_type="log",
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    figs.append(("Data context — price distribution", fig))

    # LivingArea vs price (if present).
    numeric_cols = list(payload.get("numeric_cols", []))
    if "LivingArea" in numeric_cols:
        j = numeric_cols.index("LivingArea")
        x_num = payload["X_num"][idx, j].numpy().astype(np.float64)
        stats = payload.get("num_stats", {})
        if "LivingArea" in stats:
            x_num = x_num * float(stats["LivingArea"]["std"]) + float(stats["LivingArea"]["mean"])
        fig = go.Figure()
        fig.add_trace(go.Scattergl(x=x_num, y=y_s, mode="markers", marker=dict(size=4, opacity=0.35)))
        fig.update_layout(
            title="LivingArea vs TransactionPrice (sample; log y-axis)",
            xaxis_title="LivingArea",
            yaxis_title="price ($)",
            yaxis_type="log",
            height=560,
            margin=dict(l=60, r=30, t=70, b=60),
        )
        figs.append(("Data context — LivingArea vs price", fig))

    return figs


def _read_newcommand(tex: str, name: str) -> str | None:
    m = re.search(rf"\\newcommand\{{\\{re.escape(name)}\}}\{{([^}}]+)\}}", tex)
    if not m:
        return None
    return m.group(1).strip()


def _read_pgf_table(tex: str, name: str) -> list[dict[str, str]] | None:
    """
    Read a pgfplots inline table from a LaTeX snippet like:
      \\pgfplotstableread[col sep=space]{ ... }\\Name
    """
    # Important: prevent accidentally spanning multiple pgfplotstableread blocks by
    # disallowing the literal '\pgfplotstableread' inside the captured table.
    m = re.search(
        rf"\\pgfplotstableread\[col sep=space\]\{{\s*((?:(?!\\pgfplotstableread).)*?)\s*\}}\s*\\{re.escape(name)}\b",
        tex,
        flags=re.S,
    )
    if not m:
        return None
    raw = m.group(1).strip()
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip()]
    if not lines:
        return None
    header = lines[0].split()
    out: list[dict[str, str]] = []
    for ln in lines[1:]:
        parts = ln.split()
        if len(parts) != len(header):
            # Skip malformed lines rather than crashing.
            continue
        out.append(dict(zip(header, parts)))
    return out


def _make_ann_qual_figure(qual_tex_path: Path) -> go.Figure | None:
    """
    Qualitative diagnostics for the ANN:
      - Pred vs true scatter (log space)
      - Residual histogram (log space)
      - Error by true-price decile (MdAPE% + Accuracy%)

    Data source: ann_qual_data.tex (generated by make_ann_qual_data.py).
    """
    if not qual_tex_path.exists():
        return None

    tex = qual_tex_path.read_text(encoding="utf-8", errors="replace")

    pred = _read_pgf_table(tex, "AnnPredScatter")
    resid = _read_pgf_table(tex, "AnnResidHist")
    dec = _read_pgf_table(tex, "AnnByPriceDecile")
    if pred is None or resid is None or dec is None:
        return None

    p50 = _read_newcommand(tex, "AnnApeP50")
    p90 = _read_newcommand(tex, "AnnApeP90")
    p95 = _read_newcommand(tex, "AnnApeP95")
    p99 = _read_newcommand(tex, "AnnApeP99")

    x_true = [float(r["true"]) for r in pred]
    y_pred = [float(r["pred"]) for r in pred]
    lo = float(min(min(x_true), min(y_pred)))
    hi = float(max(max(x_true), max(y_pred)))

    centers = [float(r["center"]) for r in resid]
    counts = [int(float(r["count"])) for r in resid]

    decile = [int(float(r["decile"])) for r in dec]
    acc = [float(r["acc"]) for r in dec]
    mdape_pct = [float(r["mdape"]) * 100.0 for r in dec]

    fig = make_subplots(
        rows=2,
        cols=2,
        specs=[
            [{"type": "scatter"}, {"type": "bar"}],
            [{"colspan": 2, "secondary_y": True}, None],
        ],
        subplot_titles=(
            "Predicted vs true (log space)",
            "Residual distribution (log space)",
            "Error by true-price decile",
        ),
        horizontal_spacing=0.12,
        vertical_spacing=0.18,
    )

    fig.add_trace(
        go.Scattergl(
            x=x_true,
            y=y_pred,
            mode="markers",
            name="Samples",
            marker=dict(size=6, opacity=0.55, color="#2563eb"),
            hovertemplate="true=%{x:.3f}<br>pred=%{y:.3f}<extra></extra>",
        ),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scatter(
            x=[lo, hi],
            y=[lo, hi],
            mode="lines",
            name="Ideal (y=x)",
            line=dict(color="black", dash="dash"),
            hoverinfo="skip",
        ),
        row=1,
        col=1,
    )
    fig.update_xaxes(title_text="True log1p(price)", row=1, col=1)
    fig.update_yaxes(title_text="Pred log1p(price)", row=1, col=1)

    fig.add_trace(
        go.Bar(
            x=centers,
            y=counts,
            name="Residual hist",
            marker=dict(color="rgba(37,99,235,0.25)", line=dict(color="rgba(37,99,235,0.75)", width=1)),
            hovertemplate="resid=%{x:.3f}<br>count=%{y}<extra></extra>",
        ),
        row=1,
        col=2,
    )
    fig.add_vline(x=0.0, line_width=1, line_dash="dot", line_color="black", row=1, col=2)
    fig.update_xaxes(title_text="Residual (pred − true) in log1p", row=1, col=2)
    fig.update_yaxes(title_text="Count", row=1, col=2)

    fig.add_trace(
        go.Bar(
            x=decile,
            y=mdape_pct,
            name="MdAPE (%)",
            marker=dict(color="rgba(249,115,22,0.35)", line=dict(color="rgba(249,115,22,0.85)", width=1)),
            hovertemplate="decile=%{x}<br>MdAPE=%{y:.2f}%<extra></extra>",
        ),
        row=2,
        col=1,
        secondary_y=False,
    )
    fig.add_trace(
        go.Scatter(
            x=decile,
            y=acc,
            mode="lines+markers",
            name="Accuracy (%)",
            line=dict(color="rgba(22,163,74,0.95)"),
            marker=dict(size=7),
            hovertemplate="decile=%{x}<br>Accuracy=%{y:.2f}%<extra></extra>",
        ),
        row=2,
        col=1,
        secondary_y=True,
    )
    fig.update_xaxes(title_text="True-price decile (1=lowest, 10=highest)", row=2, col=1)
    fig.update_yaxes(title_text="MdAPE (%)", row=2, col=1, secondary_y=False)
    fig.update_yaxes(title_text="Accuracy (%)", row=2, col=1, secondary_y=True)

    stats = []
    if p50 is not None:
        stats.append(f"p50={p50}%")
    if p90 is not None:
        stats.append(f"p90={p90}%")
    if p95 is not None:
        stats.append(f"p95={p95}%")
    if p99 is not None:
        stats.append(f"p99={p99}%")
    stats_str = (", ".join(stats)) if stats else ""

    fig.update_layout(
        title=f"ANN qualitative diagnostics (random split, seed=42){' — ' + stats_str if stats_str else ''}",
        height=780,
        margin=dict(l=60, r=30, t=90, b=70),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _compute_constant_baseline(payload_path: Path, *, split_strategy: str, split_seed: int) -> dict[str, float] | None:
    """
    Constant-mean baseline in log-space:
      - split: 70/15/15 using the same splitter as train_ann.py
      - predict: mean(y_log1p) over TRAIN
      - evaluate: RMSE(log1p) and MdAPE/Acc% in price space on TEST
    """
    if not payload_path.exists():
        return None

    import torch  # local import to keep script usable without torch in other envs

    # Reuse the exact splitting logic from the training code for reproducibility.
    from train_ann import make_splits

    payload = torch.load(payload_path, map_location="cpu")
    y_log1p = payload["y_log1p"].view(-1).detach().cpu().numpy().astype(np.float64)

    train_idx, _val_idx, test_idx = make_splits(
        payload=payload,
        train_frac=0.70,
        val_frac=0.15,
        test_frac=0.15,
        seed=int(split_seed),
        strategy=str(split_strategy),
    )

    y_train = y_log1p[train_idx]
    y_test = y_log1p[test_idx]
    if y_train.size == 0 or y_test.size == 0:
        return None

    pred_log = float(np.mean(y_train))
    se = (y_test - pred_log) ** 2
    rmse_log = float(np.sqrt(float(np.mean(se))))

    y_true = np.expm1(y_test)
    y_pred = float(np.expm1(pred_log))
    eps = 1e-8
    ape = np.abs(y_pred - y_true) / np.maximum(y_true, eps)
    mdape = float(np.median(ape))
    acc_pct = float(max(0.0, 100.0 * (1.0 - mdape)))

    return {
        "test_rmse": rmse_log,
        "test_mdape": mdape,
        "test_acc_pct": acc_pct,
        "seconds": 0.0,
        "n_params": 0.0,
    }


def _make_core_summary(rows: list[dict], *, split_strategy: str, const: dict[str, float] | None, split_seed: int = 42) -> go.Figure:
    """
    Core comparison focused on:
      - Constant baseline
      - Hedonic
      - Embedding+MLP ANN
      - DeepFM
      - FT-Transformer

    Uses full features and split_seed=42 for apples-to-apples comparisons.
    """

    def _pick(pred, *, metric: str, mode: str) -> dict | None:
        return _best_row(rows, pred=pred, key=metric, mode=mode)

    sseed = str(split_seed)
    labels: list[str] = []
    rmse: list[float] = []
    acc: list[float] = []
    hover: list[str] = []
    seconds: list[float] = []

    def _add(label: str, r: dict | None, *, fallback: dict[str, float] | None = None) -> None:
        if r is None and fallback is None:
            return
        labels.append(label)
        if fallback is not None:
            rmse.append(float(fallback["test_rmse"]))
            acc.append(float(fallback["test_acc_pct"]))
            seconds.append(float(fallback.get("seconds", 0.0)))
            hover.append(f"{label}<br>constant baseline<br>split_seed={split_seed}<br>split_strategy={split_strategy}")
            return
        assert r is not None
        rmse.append(float(r.get("test_rmse") or "nan"))
        acc.append(float(r.get("test_acc_pct") or "nan"))
        seconds.append(float(r.get("seconds") or 0.0))
        hover.append(_hover(r))

    _add("Constant (mean)", None, fallback=const)
    _add(
        "Hedonic",
        _pick(
            lambda r: r.get("source") == "hedonic"
            and r.get("feature_set") == "full"
            and (r.get("split_strategy") or "random") == split_strategy
            and str(r.get("split_seed") or "") == sseed,
            metric="test_rmse",
            mode="min",
        ),
    )
    _add(
        "ANN",
        _pick(
            lambda r: r.get("source") == "train_ann"
            and r.get("feature_set") == "full"
            and (r.get("split_strategy") or "random") == split_strategy
            and str(r.get("split_seed") or "") == sseed
            and (r.get("train_max_samples") or "").strip() == "",
            metric="test_rmse",
            mode="min",
        ),
    )
    _add(
        "DeepFM",
        _pick(
            lambda r: r.get("source") == "train_deepfm"
            and r.get("feature_set") == "full"
            and (r.get("split_strategy") or "random") == split_strategy
            and str(r.get("split_seed") or "") == sseed
            and (r.get("train_max_samples") or "").strip() == "",
            metric="test_rmse",
            mode="min",
        ),
    )
    _add(
        "FT-Transformer",
        _pick(
            lambda r: r.get("source") == "train_fttransformer"
            and r.get("feature_set") == "full"
            and (r.get("split_strategy") or "random") == split_strategy
            and str(r.get("split_seed") or "") == sseed
            and (r.get("train_max_samples") or "").strip() == "",
            metric="test_rmse",
            mode="min",
        ),
    )

    fig = make_subplots(rows=1, cols=2, subplot_titles=("Test RMSE (log1p)", "Test Accuracy (%)"))
    fig.add_trace(
        go.Bar(
            x=labels,
            y=rmse,
            text=[f"{v:.3f}" if v == v else "" for v in rmse],
            textposition="outside",
            hovertext=hover,
            hoverinfo="text",
            marker=dict(color=["#6b7280", "#f97316", "#2563eb", "#16a34a", "#0ea5e9"]),
        ),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Bar(
            x=labels,
            y=acc,
            text=[f"{v:.2f}%" if v == v else "" for v in acc],
            textposition="outside",
            hovertext=hover,
            hoverinfo="text",
            marker=dict(color=["#6b7280", "#f97316", "#2563eb", "#16a34a", "#0ea5e9"]),
        ),
        row=1,
        col=2,
    )
    fig.update_layout(
        title=f"Core models (feature_set=full, split_seed={split_seed}, split_strategy={split_strategy})",
        height=520,
        margin=dict(l=50, r=30, t=80, b=120),
        showlegend=False,
    )
    fig.update_xaxes(tickangle=-25)
    fig.update_yaxes(title_text="RMSE(log1p)", row=1, col=1)
    fig.update_yaxes(title_text="Accuracy (%)", row=1, col=2, rangemode="tozero")
    return fig


def _make_core_time_perf(rows: list[dict], *, split_strategy: str, const: dict[str, float] | None, split_seed: int = 42) -> go.Figure:
    """Compute vs performance scatter for the same core models as _make_core_summary."""
    # Reuse selection logic by reading off the bars we already used.
    core = _make_core_summary(rows, split_strategy=split_strategy, const=const, split_seed=split_seed)
    labels = list(core.data[0]["x"])  # type: ignore[index]
    rmse = list(core.data[0]["y"])  # type: ignore[index]
    acc = list(core.data[1]["y"])  # type: ignore[index]

    # Pull seconds/params from the underlying rows (fallback for constant baseline).
    sseed = str(split_seed)
    sec_map: dict[str, float] = {"Constant (mean)": float(const.get("seconds", 0.0) if const else 0.0)}
    param_map: dict[str, float] = {"Constant (mean)": float(const.get("n_params", 0.0) if const else 0.0)}

    def _set(label: str, pred) -> None:
        r = _best_row(rows, pred=pred, key="test_rmse", mode="min")
        if r is None:
            return
        sec_map[label] = float(r.get("seconds") or 0.0)
        param_map[label] = float(r.get("n_params") or 0.0)

    _set(
        "Hedonic",
        lambda r: r.get("source") == "hedonic"
        and r.get("feature_set") == "full"
        and (r.get("split_strategy") or "random") == split_strategy
        and str(r.get("split_seed") or "") == sseed,
    )
    _set(
        "ANN",
        lambda r: r.get("source") == "train_ann"
        and r.get("feature_set") == "full"
        and (r.get("split_strategy") or "random") == split_strategy
        and str(r.get("split_seed") or "") == sseed
        and (r.get("train_max_samples") or "").strip() == "",
    )
    _set(
        "DeepFM",
        lambda r: r.get("source") == "train_deepfm"
        and r.get("feature_set") == "full"
        and (r.get("split_strategy") or "random") == split_strategy
        and str(r.get("split_seed") or "") == sseed
        and (r.get("train_max_samples") or "").strip() == "",
    )
    _set(
        "FT-Transformer",
        lambda r: r.get("source") == "train_fttransformer"
        and r.get("feature_set") == "full"
        and (r.get("split_strategy") or "random") == split_strategy
        and str(r.get("split_seed") or "") == sseed
        and (r.get("train_max_samples") or "").strip() == "",
    )

    x = [sec_map.get(lbl, 0.0) for lbl in labels]
    y = rmse
    interp_score = {
        "Constant (mean)": 5,
        "Hedonic": 5,
        "ANN": 3,
        "DeepFM": 2,
        "FT-Transformer": 1,
    }
    c = [interp_score.get(lbl, 0) for lbl in labels]
    text = [
        f"{lbl}<br>seconds={sec_map.get(lbl, 0.0):.2f}<br>params={param_map.get(lbl, 0.0):,.0f}<br>interp={interp_score.get(lbl, 0)}<br>rmse={float(r):.3f}<br>acc={float(a):.2f}%"
        for lbl, r, a in zip(labels, rmse, acc)
    ]
    size = [max(8.0, math.log10(param_map.get(lbl, 1.0) + 10.0) * 6.0) for lbl in labels]
    fig = go.Figure(
        data=[
            go.Scatter(
                x=x,
                y=y,
                mode="markers+text",
                text=labels,
                textposition="top center",
                marker=dict(
                    size=size,
                    opacity=0.9,
                    color=c,
                    colorscale="Viridis",
                    reversescale=False,
                    showscale=True,
                    colorbar=dict(title="Interpretability<br>(higher = easier)"),
                ),
                hovertext=text,
                hoverinfo="text",
            )
        ]
    )
    fig.update_layout(
        title=f"Compute vs performance (core models; split_seed={split_seed}, split_strategy={split_strategy})<br><span style='font-size:12px;color:#666'>marker size ≈ log(params), color = interpretability score</span>",
        xaxis_title="Training time (seconds; representative run)",
        yaxis_title="Test RMSE(log1p)",
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    return fig


def _make_deepfm_seed_sensitivity(rows: list[dict]) -> go.Figure:
    """DeepFM full-train seed sensitivity for random vs time splits (feature_set=full)."""
    seeds = [0, 1, 42]
    rmse_rand = []
    rmse_time = []
    acc_rand = []
    acc_time = []
    for s in seeds:
        def _find(split: str) -> dict | None:
            return _best_row(
                rows,
                pred=lambda r: r.get("source") == "train_deepfm"
                and r.get("feature_set") == "full"
                and (r.get("split_strategy") or "random") == split
                and str(r.get("seed") or "") == str(s),
                key="test_rmse",
                mode="min",
            )

        r0 = _find("random")
        r1 = _find("time")
        rmse_rand.append(float(r0.get("test_rmse")) if r0 else float("nan"))
        rmse_time.append(float(r1.get("test_rmse")) if r1 else float("nan"))
        acc_rand.append(float(r0.get("test_acc_pct")) if r0 and (r0.get("test_acc_pct") or "").strip() else float("nan"))
        acc_time.append(float(r1.get("test_acc_pct")) if r1 and (r1.get("test_acc_pct") or "").strip() else float("nan"))

    fig = make_subplots(rows=2, cols=2, subplot_titles=("Random RMSE", "Time RMSE", "Random Acc%", "Time Acc%"))
    fig.add_trace(go.Bar(x=[str(s) for s in seeds], y=rmse_rand, text=[f"{v:.3f}" for v in rmse_rand], textposition="outside"), row=1, col=1)
    fig.add_trace(go.Bar(x=[str(s) for s in seeds], y=rmse_time, text=[f"{v:.3f}" for v in rmse_time], textposition="outside"), row=1, col=2)
    fig.add_trace(go.Bar(x=[str(s) for s in seeds], y=acc_rand, text=[f"{v:.2f}%" for v in acc_rand], textposition="outside"), row=2, col=1)
    fig.add_trace(go.Bar(x=[str(s) for s in seeds], y=acc_time, text=[f"{v:.2f}%" for v in acc_time], textposition="outside"), row=2, col=2)
    fig.update_layout(
        title="DeepFM seed sensitivity (full train; feature_set=full)",
        height=650,
        margin=dict(l=60, r=30, t=80, b=60),
        showlegend=False,
    )
    fig.update_yaxes(title_text="Test RMSE(log1p)", row=1, col=1)
    fig.update_yaxes(title_text="Test RMSE(log1p)", row=1, col=2)
    fig.update_yaxes(title_text="Test Accuracy (%)", row=2, col=1, rangemode="tozero")
    fig.update_yaxes(title_text="Test Accuracy (%)", row=2, col=2, rangemode="tozero")
    fig.update_xaxes(title_text="Seed", row=1, col=1)
    fig.update_xaxes(title_text="Seed", row=1, col=2)
    fig.update_xaxes(title_text="Seed", row=2, col=1)
    fig.update_xaxes(title_text="Seed", row=2, col=2)
    return fig


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", default="results_all.csv")
    parser.add_argument("--feature-importance", default="feature_importance_results.csv")
    parser.add_argument("--data-pt", default="ann_tensors_full.pt")
    parser.add_argument("--ann-qual-tex", default="ann_qual_data.tex")
    parser.add_argument("--out", default="plots/report_graphs.html")
    parser.add_argument("--sample-n", type=int, default=100_000)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    results_path = Path(args.results)
    rows = _load_csv_rows(results_path)
    if not rows:
        raise SystemExit(f"No rows found in {results_path}")

    sections: list[str] = []
    fig_registry: list[dict] = []
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>RPSAps360 — Report Graphs</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif; margin: 24px; background: #fafafa; }}
    h1 {{ margin: 0 0 6px 0; }}
    .meta {{ color: #555; margin-bottom: 18px; }}
    .grid {{ display: grid; grid-template-columns: 1fr; gap: 16px; }}
    .card {{ background: white; border: 1px solid #eee; border-radius: 12px; padding: 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }}
    .card h2 {{ margin: 0; font-size: 16px; }}
    .card-head {{ display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 10px; }}
    .actions {{ display: flex; gap: 8px; flex-wrap: wrap; }}
    .btn {{ border: 1px solid #ddd; background: #111; color: #fff; border-radius: 10px; padding: 8px 10px; font-size: 12px; cursor: pointer; text-decoration: none; display: inline-block; }}
    .btn.secondary {{ background: #fff; color: #111; }}
    .btn:hover {{ filter: brightness(0.95); }}
    .note {{ color: #666; font-size: 13px; line-height: 1.4; }}
    code {{ background: #f2f2f2; padding: 1px 5px; border-radius: 6px; }}
  </style>
  <script type="text/javascript">{get_plotlyjs()}</script>
  <script type="text/javascript">
    async function downloadFig(id, format, filename) {{
      try {{
        const gd = document.getElementById(id);
        if (!gd) {{
          alert("Chart not found: " + id);
          return;
        }}
        await Plotly.downloadImage(gd, {{
          format: format,
          filename: filename,
          scale: 2
        }});
      }} catch (e) {{
        console.error(e);
        alert("Download failed. See console for details.");
      }}
    }}

    async function downloadAll(format) {{
      const figs = (window.__FIG_REGISTRY || []);
      if (!figs.length) {{
        alert("No charts found to download.");
        return;
      }}
      // Browsers may block multiple downloads; you may need to allow them.
      for (const fig of figs) {{
        await downloadFig(fig.id, format, fig.filename);
        await new Promise(r => setTimeout(r, 150));
      }}
    }}
  </script>
</head>
<body>
  <h1>RPSAps360 — Report Graphs</h1>
  <div class="meta">Generated {now} from <code>{results_path}</code>. Use the download buttons (or each chart’s modebar) to save PNG/SVG.</div>
  <div class="note card">
    These plots focus on <b>feature_set=full</b>. Sweeps often use <b>train_max_samples=50,000</b> for speed; the best ANN/DeepFM results include full-train runs.
  </div>
  <div class="card">
    <div class="card-head">
      <h2>Quick links</h2>
      <div class="actions">
        <a class="btn secondary" href="../final_report.tex">Final report (LaTeX)</a>
        <a class="btn secondary" href="../graphs_report.tex">Graphs appendix (LaTeX)</a>
        <a class="btn secondary" href="../results_all.csv">results_all.csv</a>
      </div>
    </div>
    <div class="note">No LaTeX installed? Run <code>python make_overleaf_bundle.py</code> and upload the zip to Overleaf.</div>
  </div>
  <div class="card">
    <div class="card-head">
      <h2>Downloads</h2>
      <div class="actions">
        <button class="btn" onclick="downloadAll('png')">Download all PNG</button>
        <button class="btn secondary" onclick="downloadAll('svg')">Download all SVG</button>
      </div>
    </div>
    <div class="note">Tip: Each chart also has its own download buttons above it. Your browser may ask you to allow multiple downloads.</div>
  </div>
  <div class="grid">
"""

    # Core-model comparisons (what we mostly care about in the final report).
    const_random = _compute_constant_baseline(Path(args.data_pt), split_strategy="random", split_seed=42)
    const_time = _compute_constant_baseline(Path(args.data_pt), split_strategy="time", split_seed=42)
    _add_fig_section(
        sections,
        "Core models — random split (constant/hedonic/ANN/DeepFM/FT-Transformer)",
        _make_core_summary(rows, split_strategy="random", const=const_random, split_seed=42),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Core models — time split (constant/hedonic/ANN/DeepFM/FT-Transformer)",
        _make_core_summary(rows, split_strategy="time", const=const_time, split_seed=42),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Core models — compute vs RMSE (training seconds vs test RMSE)",
        _make_core_time_perf(rows, split_strategy="random", const=const_random, split_seed=42),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "DeepFM — seed sensitivity (full train)",
        _make_deepfm_seed_sensitivity(rows),
        registry=fig_registry,
    )

    # Qualitative diagnostics (ANN) if the LaTeX snippet exists.
    ann_qual_fig = _make_ann_qual_figure(Path(args.ann_qual_tex))
    if ann_qual_fig is not None:
        _add_fig_section(
            sections,
            "Qualitative diagnostics (ANN): pred vs true + residuals + error by decile",
            ann_qual_fig,
            registry=fig_registry,
        )

    # Best-by bars.
    _add_fig_section(
        sections,
        "Best per model family — Test RMSE (full features, random split)",
        _make_best_bar(rows, metric="test_rmse", mode="min", title="Best run per family by test_rmse"),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Best per model family — Test accuracy% (full features, random split)",
        _make_best_bar(rows, metric="test_acc_pct", mode="max", title="Best run per family by test_acc_pct"),
        registry=fig_registry,
    )

    # Sweeps.
    _add_fig_section(sections, "Sweep trade-off: RMSE vs accuracy% (each point = one run)", _make_sweep_scatter(rows, title="Sweeps: test_rmse vs test_acc_pct"), registry=fig_registry)
    _add_fig_section(sections, "Sweep correlation: validation accuracy% vs test accuracy%", _make_val_vs_test(rows, title="Sweeps: val_acc_pct vs test_acc_pct"), registry=fig_registry)
    _add_fig_section(sections, "Sweep distributions: test RMSE", _make_rmse_hist(rows, title="Sweeps: distribution of test_rmse"), registry=fig_registry)
    _add_fig_section(
        sections,
        "Overfitting signal: validation accuracy gap (best checkpoint − last epoch)",
        _make_overfit_box(
            rows,
            title="Overfitting proxy: val_acc_pct - val_acc_pct_last (positive means last epoch worse)",
            metric_best="val_acc_pct",
            metric_last="val_acc_pct_last",
            y_title="val_acc_pct - val_acc_pct_last",
        ),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Overfitting signal: validation RMSE gap (last epoch − best checkpoint)",
        _make_overfit_box(
            rows,
            title="Overfitting proxy: val_rmse_last - val_rmse (positive means last epoch worse)",
            metric_best="val_rmse_last",
            metric_last="val_rmse",
            y_title="val_rmse_last - val_rmse",
        ),
        registry=fig_registry,
    )

    # Robustness eval suite.
    _add_fig_section(
        sections,
        "Robustness (random split): test RMSE across split/model seeds",
        _make_eval_points(rows, split_strategy="random", metric="test_rmse", title="eval_suite: test_rmse (random split)"),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Robustness (random split): test accuracy% across split/model seeds",
        _make_eval_points(rows, split_strategy="random", metric="test_acc_pct", title="eval_suite: test_acc_pct (random split)"),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Robustness (time split): test RMSE across model seeds",
        _make_eval_points(rows, split_strategy="time", metric="test_rmse", title="eval_suite: test_rmse (time split)"),
        registry=fig_registry,
    )
    _add_fig_section(
        sections,
        "Robustness summary: mean ± std (random vs time)",
        _make_eval_mean_bars(rows, metric="test_rmse", title="eval_suite: mean test_rmse by split strategy"),
        registry=fig_registry,
    )

    # Feature importance (if present).
    fi_path = Path(args.feature_importance)
    for title, fig in _make_feature_importance(fi_path):
        _add_fig_section(sections, title, fig, registry=fig_registry)

    # Data context (optional, if tensors exist).
    for title, fig in _make_data_context(Path(args.data_pt), sample_n=args.sample_n, seed=args.seed):
        _add_fig_section(sections, title, fig, registry=fig_registry)

    footer = f"""
  </div>
  <script type="text/javascript">
    window.__FIG_REGISTRY = {json.dumps(fig_registry, ensure_ascii=False)};
  </script>
</body>
</html>
"""

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + "\n".join(sections) + footer, encoding="utf-8")
    print("Wrote:", out_path.resolve())


if __name__ == "__main__":
    main()
