#!/usr/bin/env python3
"""
Generate lots of report-ready graphs from the single canonical results CSV.

Why HTML (Plotly) instead of PNG:
  - This environment's compiled plotting stack (matplotlib) is broken due to
    a NumPy ABI mismatch, but Plotly graph_objects works fine and produces
    interactive, exportable charts.
  - In the HTML, each chart has a camera icon ("Download plot as png").

Inputs:
  - results_all.csv (required; tracked)
  - feature_importance_results.csv (optional; generated by feature_importance.py)
  - ann_tensors_full.pt (optional; for a few dataset context charts)

Output:
  - plots/report_graphs.html (generated; should be gitignored)
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import math
import random
from pathlib import Path
from statistics import mean, stdev

import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
from plotly.offline import get_plotlyjs
from plotly.subplots import make_subplots


def _load_csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _f(v: object) -> float | None:
    try:
        s = str(v).strip()
        if s == "":
            return None
        return float(s)
    except Exception:
        return None


def _i(v: object) -> int | None:
    try:
        s = str(v).strip()
        if s == "":
            return None
        return int(float(s))
    except Exception:
        return None


def _is_full_random(row: dict) -> bool:
    return (row.get("feature_set") == "full") and ((row.get("split_strategy") or "random") == "random")


def _best_row(rows: list[dict], *, pred, key: str, mode: str) -> dict | None:
    best: dict | None = None
    best_val: float | None = None
    for r in rows:
        if not pred(r):
            continue
        v = _f(r.get(key, ""))
        if v is None or math.isnan(v):
            continue
        if best is None:
            best, best_val = r, v
            continue
        assert best_val is not None
        if mode == "min" and v < best_val:
            best, best_val = r, v
        elif mode == "max" and v > best_val:
            best, best_val = r, v
    return best


def _short_name(row: dict) -> str:
    src = row.get("source", "")
    if src == "train_ann":
        return f"train_ann:{row.get('run_name','')}"
    if src == "hedonic":
        return "hedonic"
    return str(row.get("name", "") or row.get("run_name", "") or "").strip()


def _hover(row: dict) -> str:
    parts = [
        f"source={row.get('source','')}",
        f"stage={row.get('stage','')}",
        f"model={row.get('model','')}",
        f"feature_set={row.get('feature_set','')}",
        f"split_strategy={row.get('split_strategy','')}",
        f"split_seed={row.get('split_seed','')}",
        f"seed={row.get('seed','')}",
        f"train_max_samples={row.get('train_max_samples','')}",
        f"name={_short_name(row)}",
        f"test_rmse={row.get('test_rmse','')}",
        f"test_acc_pct={row.get('test_acc_pct','')}",
        f"val_rmse={row.get('val_rmse','')}",
        f"val_acc_pct={row.get('val_acc_pct','')}",
        f"val_acc_pct_last={row.get('val_acc_pct_last','')}",
    ]
    return "<br>".join(parts)


def _add_fig_section(sections: list[str], title: str, fig: go.Figure) -> None:
    div = pio.to_html(
        fig,
        include_plotlyjs=False,
        full_html=False,
        config={
            "displaylogo": False,
            "responsive": True,
        },
    )
    sections.append(f"<section class='card'><h2>{title}</h2>{div}</section>")


def _make_best_bar(rows: list[dict], *, metric: str, mode: str, title: str) -> go.Figure:
    families = [
        ("ANN (full train)", lambda r: r.get("source") == "train_ann" and _is_full_random(r)),
        ("Hedonic (full train)", lambda r: r.get("source") == "hedonic" and _is_full_random(r)),
        ("DeepFM sweep (50k)", lambda r: r.get("source") == "sweep_deepfm" and _is_full_random(r)),
        ("ANN sweep (deep_test, 50k)", lambda r: r.get("source") == "sweep_deep_test" and _is_full_random(r)),
        ("ANN sweep (clean, 50k)", lambda r: r.get("source") == "sweep_clean" and _is_full_random(r)),
        ("FM sweep (50k)", lambda r: r.get("source") == "sweep_fm" and _is_full_random(r)),
        ("TabNet sweep (50k)", lambda r: r.get("source") == "sweep_tabnet" and _is_full_random(r)),
    ]

    picked: list[tuple[str, dict]] = []
    for label, pred in families:
        r = _best_row(rows, pred=pred, key=metric, mode=mode)
        if r is None:
            continue
        picked.append((label, r))

    # Sort by the metric (direction-aware) for readability.
    picked.sort(key=lambda kv: _f(kv[1].get(metric, "")) or (float("inf") if mode == "min" else -float("inf")), reverse=(mode == "max"))

    x = [lbl for lbl, _ in picked]
    y = [_f(r.get(metric, "")) for _, r in picked]
    text = []
    hover = []
    for _, r in picked:
        acc = _f(r.get("test_acc_pct", ""))
        rmse = _f(r.get("test_rmse", ""))
        if metric == "test_rmse":
            text.append(f"{rmse:.3f}" if rmse is not None else "")
        else:
            text.append(f"{acc:.2f}%" if acc is not None else "")
        hover.append(_hover(r))

    fig = go.Figure(
        data=[
            go.Bar(
                x=x,
                y=y,
                text=text,
                textposition="outside",
                hovertext=hover,
                hoverinfo="text",
            )
        ]
    )
    fig.update_layout(
        title=title,
        yaxis_title=metric,
        xaxis_title="Model family (best run per family)",
        height=520,
        margin=dict(l=50, r=30, t=70, b=120),
    )
    fig.update_xaxes(tickangle=-25)
    return fig


def _make_sweep_scatter(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("ANN sweep (clean)", "sweep_clean"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]

    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("test_rmse", ""))
            y = _f(r.get("test_acc_pct", ""))
            if x is None or y is None:
                continue
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                opacity=0.55,
                marker=dict(size=7),
                hovertext=hover,
                hoverinfo="text",
            )
        )

    fig.update_layout(
        title=title,
        xaxis_title="Test RMSE (log1p price) — lower is better",
        yaxis_title="Test accuracy % (MdAPE-based) — higher is better",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_val_vs_test(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("val_acc_pct", ""))
            y = _f(r.get("test_acc_pct", ""))
            if x is None or y is None:
                continue
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                opacity=0.55,
                marker=dict(size=7),
                hovertext=hover,
                hoverinfo="text",
            )
        )
    fig.update_layout(
        title=title,
        xaxis_title="Validation accuracy % (MdAPE-based)",
        yaxis_title="Test accuracy % (MdAPE-based)",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_rmse_hist(rows: list[dict], *, title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        xs: list[float] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            x = _f(r.get("test_rmse", ""))
            if x is None:
                continue
            xs.append(x)
        if not xs:
            continue
        fig.add_trace(go.Histogram(x=xs, name=label, opacity=0.55, nbinsx=60))
    fig.update_layout(
        title=title,
        barmode="overlay",
        xaxis_title="Test RMSE (log1p price)",
        yaxis_title="Count",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0.0),
    )
    return fig


def _make_overfit_box(rows: list[dict], *, title: str, metric_best: str, metric_last: str, y_title: str) -> go.Figure:
    sources = [
        ("ANN sweep (deep_test)", "sweep_deep_test"),
        ("FM sweep", "sweep_fm"),
        ("DeepFM sweep", "sweep_deepfm"),
        ("TabNet sweep", "sweep_tabnet"),
    ]
    fig = go.Figure()
    for label, src in sources:
        ys: list[float] = []
        for r in rows:
            if r.get("source") != src:
                continue
            if not _is_full_random(r):
                continue
            a = _f(r.get(metric_best, ""))
            b = _f(r.get(metric_last, ""))
            if a is None or b is None:
                continue
            ys.append(a - b)
        if not ys:
            continue
        fig.add_trace(go.Box(y=ys, name=label, boxmean="sd"))
    fig.update_layout(
        title=title,
        yaxis_title=y_title,
        height=520,
        margin=dict(l=60, r=30, t=70, b=80),
    )
    return fig


def _make_eval_points(rows: list[dict], *, split_strategy: str, metric: str, title: str) -> go.Figure:
    eval_rows = [r for r in rows if r.get("source") == "eval_suite" and (r.get("split_strategy") == split_strategy)]
    # run_name identifies the model family in eval_suite.
    run_names = [
        ("ANN best config", "ann_best_full"),
        ("Hedonic baseline", "hedonic_full"),
    ]
    fig = go.Figure()
    for label, rn in run_names:
        xs: list[float] = []
        ys: list[float] = []
        hover: list[str] = []
        for r in eval_rows:
            if r.get("run_name") != rn:
                continue
            split_seed = _i(r.get("split_seed", ""))
            seed = _i(r.get("seed", ""))
            y = _f(r.get(metric, ""))
            if split_seed is None or seed is None or y is None:
                continue
            # small jitter so overlapping seeds are visible
            x = float(split_seed) + (float(seed) - 0.5) * 0.15
            xs.append(x)
            ys.append(y)
            hover.append(_hover(r))
        if not xs:
            continue
        fig.add_trace(
            go.Scatter(
                x=xs,
                y=ys,
                mode="markers",
                name=label,
                marker=dict(size=11),
                hovertext=hover,
                hoverinfo="text",
            )
        )
    fig.update_layout(
        title=title,
        xaxis_title="Split seed (jittered by model seed)",
        yaxis_title=metric,
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    return fig


def _make_eval_mean_bars(rows: list[dict], *, metric: str, title: str) -> go.Figure:
    eval_rows = [r for r in rows if r.get("source") == "eval_suite" and r.get("feature_set") == "full"]
    groups = [
        ("ANN best config", "ann_best_full"),
        ("Hedonic baseline", "hedonic_full"),
    ]
    strategies = ["random", "time"]

    fig = go.Figure()
    for label, rn in groups:
        ys = []
        err = []
        for strat in strategies:
            vals = [_f(r.get(metric, "")) for r in eval_rows if r.get("run_name") == rn and r.get("split_strategy") == strat]
            vals = [v for v in vals if v is not None]
            if not vals:
                ys.append(None)
                err.append(0.0)
            else:
                ys.append(mean(vals))
                err.append(stdev(vals) if len(vals) > 1 else 0.0)
        fig.add_trace(
            go.Bar(
                x=strategies,
                y=ys,
                name=label,
                error_y=dict(type="data", array=err, visible=True),
            )
        )
    fig.update_layout(
        title=title,
        barmode="group",
        xaxis_title="Split strategy",
        yaxis_title=metric,
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    return fig


def _make_feature_importance(fi_path: Path) -> list[tuple[str, go.Figure]]:
    rows = _load_csv_rows(fi_path)
    if not rows:
        return []

    out: list[tuple[str, go.Figure]] = []
    for model in ["ann_mlp", "hedonic_linear_fixed_effects"]:
        subset = [r for r in rows if r.get("model") == model]
        subset.sort(key=lambda r: float(r.get("delta_val_mse", "0") or 0.0), reverse=True)
        top = subset[:15]
        names = [f"{r.get('feature_type')}:{r.get('feature_name')}" for r in top][::-1]
        vals = [float(r.get("delta_val_mse", "0") or 0.0) for r in top][::-1]
        fig = go.Figure(data=[go.Bar(x=vals, y=names, orientation="h")])
        fig.update_layout(
            title=f"Permutation importance (top 15 by Δval_mse) — {model}",
            xaxis_title="Increase in validation MSE when permuted (Δval_mse)",
            yaxis_title="Feature",
            height=620,
            margin=dict(l=180, r=30, t=70, b=60),
        )
        out.append((f"Feature importance — {model}", fig))

    # ANN vs Hedonic scatter for shared features.
    by_feat: dict[str, dict[str, float]] = {}
    for r in rows:
        key = f"{r.get('feature_type')}:{r.get('feature_name')}"
        by_feat.setdefault(key, {})
        by_feat[key][r.get("model", "")] = float(r.get("delta_val_mse", "0") or 0.0)
    xs = []
    ys = []
    text = []
    for feat, d in by_feat.items():
        if "ann_mlp" not in d or "hedonic_linear_fixed_effects" not in d:
            continue
        xs.append(d["hedonic_linear_fixed_effects"])
        ys.append(d["ann_mlp"])
        text.append(feat)

    max_v = max(xs + ys) if xs and ys else 1.0
    line = np.linspace(0, max_v, 50)
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=line, y=line, mode="lines", name="y=x", line=dict(dash="dash")))
    fig.add_trace(go.Scatter(x=xs, y=ys, mode="markers", name="Features", text=text, hoverinfo="text+x+y"))
    fig.update_layout(
        title="Permutation importance comparison (Δval_mse): ANN vs Hedonic",
        xaxis_title="Δval_mse (hedonic)",
        yaxis_title="Δval_mse (ANN)",
        height=560,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    out.append(("Feature importance — ANN vs Hedonic", fig))
    return out


def _make_data_context(payload_path: Path, *, sample_n: int, seed: int) -> list[tuple[str, go.Figure]]:
    if not payload_path.exists():
        return []
    import torch  # local import to keep script usable without torch in other envs

    payload = torch.load(payload_path, map_location="cpu")
    y_log = payload["y_log1p"].view(-1)

    n = int(y_log.shape[0])
    rng = random.Random(seed)
    idx = rng.sample(range(n), k=min(sample_n, n))
    y_log_s = y_log[idx].numpy()
    y_s = np.expm1(y_log_s)

    figs: list[tuple[str, go.Figure]] = []

    fig = go.Figure()
    fig.add_trace(go.Histogram(x=y_log_s, nbinsx=80))
    fig.update_layout(
        title="Target distribution: log1p(TransactionPrice) (sample)",
        xaxis_title="log1p(price)",
        yaxis_title="Count",
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    figs.append(("Data context — log1p(price) distribution", fig))

    fig = go.Figure()
    fig.add_trace(go.Histogram(x=y_s, nbinsx=80))
    fig.update_layout(
        title="Target distribution: TransactionPrice (sample; log x-axis)",
        xaxis_title="price ($)",
        yaxis_title="Count",
        xaxis_type="log",
        height=520,
        margin=dict(l=60, r=30, t=70, b=60),
    )
    figs.append(("Data context — price distribution", fig))

    # LivingArea vs price (if present).
    numeric_cols = list(payload.get("numeric_cols", []))
    if "LivingArea" in numeric_cols:
        j = numeric_cols.index("LivingArea")
        x_num = payload["X_num"][idx, j].numpy().astype(np.float64)
        stats = payload.get("num_stats", {})
        if "LivingArea" in stats:
            x_num = x_num * float(stats["LivingArea"]["std"]) + float(stats["LivingArea"]["mean"])
        fig = go.Figure()
        fig.add_trace(go.Scattergl(x=x_num, y=y_s, mode="markers", marker=dict(size=4, opacity=0.35)))
        fig.update_layout(
            title="LivingArea vs TransactionPrice (sample; log y-axis)",
            xaxis_title="LivingArea",
            yaxis_title="price ($)",
            yaxis_type="log",
            height=560,
            margin=dict(l=60, r=30, t=70, b=60),
        )
        figs.append(("Data context — LivingArea vs price", fig))

    return figs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", default="results_all.csv")
    parser.add_argument("--feature-importance", default="feature_importance_results.csv")
    parser.add_argument("--data-pt", default="ann_tensors_full.pt")
    parser.add_argument("--out", default="plots/report_graphs.html")
    parser.add_argument("--sample-n", type=int, default=100_000)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    results_path = Path(args.results)
    rows = _load_csv_rows(results_path)
    if not rows:
        raise SystemExit(f"No rows found in {results_path}")

    sections: list[str] = []
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>RPSAps360 — Report Graphs</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif; margin: 24px; background: #fafafa; }}
    h1 {{ margin: 0 0 6px 0; }}
    .meta {{ color: #555; margin-bottom: 18px; }}
    .grid {{ display: grid; grid-template-columns: 1fr; gap: 16px; }}
    .card {{ background: white; border: 1px solid #eee; border-radius: 12px; padding: 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }}
    .card h2 {{ margin: 0 0 10px 0; font-size: 16px; }}
    .note {{ color: #666; font-size: 13px; line-height: 1.4; }}
    code {{ background: #f2f2f2; padding: 1px 5px; border-radius: 6px; }}
  </style>
  <script type="text/javascript">{get_plotlyjs()}</script>
</head>
<body>
  <h1>RPSAps360 — Report Graphs</h1>
  <div class="meta">Generated {now} from <code>{results_path}</code>. Use each chart’s modebar to download PNG.</div>
  <div class="note card">
    These plots focus on <b>feature_set=full</b>. Sweeps often use <b>train_max_samples=50,000</b> for speed; the best ANN result is a full-train run.
  </div>
  <div class="grid">
"""

    # Best-by bars.
    _add_fig_section(
        sections,
        "Best per model family — Test RMSE (full features, random split)",
        _make_best_bar(rows, metric="test_rmse", mode="min", title="Best run per family by test_rmse"),
    )
    _add_fig_section(
        sections,
        "Best per model family — Test accuracy% (full features, random split)",
        _make_best_bar(rows, metric="test_acc_pct", mode="max", title="Best run per family by test_acc_pct"),
    )

    # Sweeps.
    _add_fig_section(sections, "Sweep trade-off: RMSE vs accuracy% (each point = one run)", _make_sweep_scatter(rows, title="Sweeps: test_rmse vs test_acc_pct"))
    _add_fig_section(sections, "Sweep correlation: validation accuracy% vs test accuracy%", _make_val_vs_test(rows, title="Sweeps: val_acc_pct vs test_acc_pct"))
    _add_fig_section(sections, "Sweep distributions: test RMSE", _make_rmse_hist(rows, title="Sweeps: distribution of test_rmse"))
    _add_fig_section(
        sections,
        "Overfitting signal: validation accuracy gap (best checkpoint − last epoch)",
        _make_overfit_box(
            rows,
            title="Overfitting proxy: val_acc_pct - val_acc_pct_last (positive means last epoch worse)",
            metric_best="val_acc_pct",
            metric_last="val_acc_pct_last",
            y_title="val_acc_pct - val_acc_pct_last",
        ),
    )
    _add_fig_section(
        sections,
        "Overfitting signal: validation RMSE gap (last epoch − best checkpoint)",
        _make_overfit_box(
            rows,
            title="Overfitting proxy: val_rmse_last - val_rmse (positive means last epoch worse)",
            metric_best="val_rmse_last",
            metric_last="val_rmse",
            y_title="val_rmse_last - val_rmse",
        ),
    )

    # Robustness eval suite.
    _add_fig_section(
        sections,
        "Robustness (random split): test RMSE across split/model seeds",
        _make_eval_points(rows, split_strategy="random", metric="test_rmse", title="eval_suite: test_rmse (random split)"),
    )
    _add_fig_section(
        sections,
        "Robustness (random split): test accuracy% across split/model seeds",
        _make_eval_points(rows, split_strategy="random", metric="test_acc_pct", title="eval_suite: test_acc_pct (random split)"),
    )
    _add_fig_section(
        sections,
        "Robustness (time split): test RMSE across model seeds",
        _make_eval_points(rows, split_strategy="time", metric="test_rmse", title="eval_suite: test_rmse (time split)"),
    )
    _add_fig_section(
        sections,
        "Robustness summary: mean ± std (random vs time)",
        _make_eval_mean_bars(rows, metric="test_rmse", title="eval_suite: mean test_rmse by split strategy"),
    )

    # Feature importance (if present).
    fi_path = Path(args.feature_importance)
    for title, fig in _make_feature_importance(fi_path):
        _add_fig_section(sections, title, fig)

    # Data context (optional, if tensors exist).
    for title, fig in _make_data_context(Path(args.data_pt), sample_n=args.sample_n, seed=args.seed):
        _add_fig_section(sections, title, fig)

    footer = """
  </div>
</body>
</html>
"""

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + "\n".join(sections) + footer, encoding="utf-8")
    print("Wrote:", out_path.resolve())


if __name__ == "__main__":
    main()

